version: '3.9'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./out:/app/out
    environment:
      - NODE_ENV=production
      - ELECTRON_FORCE_ARM64=1
      - npm_config_arch=arm64
      - npm_config_target_arch=arm64